language: java

os:
- linux

complier:
- javac

jdk:
- oraclejdk8
- oraclejdk7
- openjdk6

install: true 

sudo:
- required

script:
- cd Application\ Code && make && make testscript
